### ISSUE TITLE
Train Custom Data

### ISSUE THREAD

**Issue by lilin19890401** [tianyu0207/PEBAL#12]
hi author,
              thank you for your great work and open source.
              I want to train model in my own custom data, for example: this data have only three inlier classes, and we want use this model to determine outlier. Can you support some training tutorial for custom data?not coco or cityscapes.
              Thanks.
.

**Comment by yyliu01** [comment]
Hi Lin,

The approach acquires an outlier dataset for the outlier exposures so that you'll need a dataset that contains pixel-wise annotation and also does not overlap with your inlier categories. This outlier dataset doesn't need to contain lots of images, > 50 can do the deal.

If it can be fulfilled, that customised dataset training can be split into 2 steps:
1). only training the inlier dataset normally and save the checkpoint, and
2). load the checkpoint & fix the entire network except the last convolutional block to perform the PEBAL (with 1 external channel, you can adjust it in the "config.yml" file.

Please note, in step 2), the learning rate should be 10 times lower compared with normal training (i.e., step 1)).

Good luck.

Yuyuan
