### ISSUE TITLE
EBM loss on D_out formula seems wrong

### ISSUE THREAD

**Issue by luoyuchenmlcv** [tianyu0207/PEBAL#20]
In the paper, the energy based model to train on D_out is shown as bellow:
![image](https://user-images.githubusercontent.com/102636806/188126975-9c86a1ff-eb0f-4919-b42e-2da35df75f12.png)

![image](https://user-images.githubusercontent.com/102636806/188126320-93560d3c-7246-4fa7-8c1e-4406770e0f98.png)
However,  this formula seems to treat all pixels ω for an image in D_out as ood pixels, but D_out is like this: only the cyan part is ood, the rest are inliers, they should be trained using **L_ebm^in** instead, right?
![image](https://user-images.githubusercontent.com/102636806/188126672-9051faa4-2f87-4895-89ba-4a080ffff21b.png)

**Comment by tianyu0207** [comment]
> In the paper, the energy based model to train on D_out is shown as bellow: ![image](https://user-images.githubusercontent.com/102636806/188126975-9c86a1ff-eb0f-4919-b42e-2da35df75f12.png)
> 
> ![image](https://user-images.githubusercontent.com/102636806/188126320-93560d3c-7246-4fa7-8c1e-4406770e0f98.png) However, this formula seems to treat all pixels ω for an image in D_out as ood pixels, but D_out is like this: only the cyan part is ood, the rest are inliers, they should be trained using **L_ebm^in** instead, right? ![image](https://user-images.githubusercontent.com/102636806/188126672-9051faa4-2f87-4895-89ba-4a080ffff21b.png)

Hi thanks for your interest to our work and sorry for the confusion. Another issue also pointed out this confusion and we have fixed the texts that may lead to misunderstandings in the Arxiv version. D_out should be trained with both ebm_in and ebm_out because they contain both inlier and outlier pixels. 

I'm closing the issues now and feel free to reopen it if needed.
