### ISSUE TITLE
Fishyscape test result 

### ISSUE THREAD

**Issue by hyunjunChhoi** [tianyu0207/PEBAL#27]
Thanks for your great work.

I can get the validation result as following instruction.

Fishy scape test result (benchmark result from https://fishyscapes.com/results)

can be achieved by  the same checkpoint that you provided  ?? 

Or other checkpoints or something else  ??

**Comment by tianyu0207** [comment]
> Thanks for your great work.
> 
> I can get the validation result as following instruction.
> 
> Fishy scape test result (benchmark result from https://fishyscapes.com/results)
> 
> can be achieved by the same checkpoint that you provided ??
> 
> Or other checkpoints or something else ??

Hi, we share the checkpoint with the best results on Fishyscape Val set and RoadAnomaly. For LostandFound Testing, we have a different checkpoint due to scene differences. You could select a common checkpoint for all possible dataset but may have slightly lower performance than showed in the paper. For the Fishyscape leaderboard, we submit a total of 5 checkpoints and this is the final checkpoint listed as 'Rev5' on their website.
