### ISSUE TITLE
Some more guide to data preperation?

### ISSUE THREAD

**Issue by imesu2378** [tianyu0207/PEBAL#4]
Hi, thank you for your great work.

I've been trying to train your model but currently I'm finding it impossible to prepare the datasets (cityscapes, coco) in the form that is required for your code.

If possible can you please provide the preprocessed datasets directly?

Thanks a bunch.

**Comment by yyliu01** [comment]
Thanks for your interest, but we cannot provide the preprocessed dataset due to the copyright issue.  As you can see, there is no one offers the processed cityscape on GitHub.

In more detail,
1). for the cityscape, you'll have to spend time to read and hack the code in [here](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py). All you need to do is convert the label into 19 classes, instead of the 35.

2). for the CoCo, you'll only need to download the dataset and run this [script](https://github.com/robin-chan/meta-ood/blob/master/preparation/prepare_coco_segmentation.py) directly.

Regards,
Yuyuan

**Comment by yyliu01** [comment]
I'm closing the issue, but feel free to reopen it if your problem is still not be solved.
